name: persian_datepicker
description: A simple shamsi date picker.
version: 0.1.0
author: Ashkan Tofangdar
repository: https://github.com/Ashkan4472/persian_datepicker_flutter_package

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shamsi_date: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
